=== nschoena/golf_score_tracker/data/courses/course.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/my-data.schema.json",
  "title": "Course document schema",
  "description": "The schema for the course document I am designing.",
  "type": "object",
  "properties": {
    "courseId": {
        "type": "integer",
        "description": "Unique number that will serve as primary key for the courses document database"
    },
    "courseName": {
        "type": "string",
        "description": "The name of the golf course."    
    },
    "tees": {
        "type": "string",
        "description": "Name of tees."
    },
    "courseSide": {
        "type": "string",
        "description": "Course section: Front 9, Back 9, or Full 18",
        "enum": [
            "Front",
            "Back",
            "All"
        ]
    },
    "location": {
        "type": "string",
        "description": "Where the course is located."
    },
    "rating": {
        "type": "number",
        "description": "Course rating."
    },
    "slope": {
        "type": "integer",
        "description": "Course slope."
    },
    "yardage": {
        "type": "integer",
        "description": "Total yards for this section of the course."
    },
    "par": {
        "type": "integer",
        "description": "Par for this section of the course."
    },
    "holes": {
        "type": "array",
        "description": "An ordered list of golf holes for the course.",        
        "minItems": 9,
        "maxItems": 18,
        "items": {
            "type": "object",
            "properties": {
                "holeNumber": {"type": "integer"},
                "yardage": {"type": "integer"},
                "par": {"type": "integer"},
                "handicap": {"type": "integer"}                
            }
        }
    }

  },
  "required": [
    "courseId",
    "courseName",
    "tees",
    "courseSide",
    "location",    
    "rating",
    "slope",
    "par",
    "holes"
  ]
}

=== nschoena/golf_score_tracker/data/courses/village_green_white.json
{
  "$schema": "./course.schema.json",
  "courseId": 0,
  "courseName": "Village Green Golf Course",
  "tees": "White",
  "courseSide": "All",
  "location": "Moorhead, MN",
  "rating": 70.9,
  "slope": 128,
  "yardage": 6352,
  "par": 72,
  "holes": [
    {
      "holeNumber": 1,
      "yardage": 351,
      "par": 4,
      "handicap": 13
    },
    {
      "holeNumber": 2,
      "yardage": 390,
      "par": 4,
      "handicap": 1
    },
    {
      "holeNumber": 3,
      "yardage": 507,
      "par": 5,
      "handicap": 5
    },
    {
      "holeNumber": 4,
      "yardage": 141,
      "par": 3,
      "handicap": 15
    },
    {
      "holeNumber": 5,
      "yardage": 520,
      "par": 5,
      "handicap": 7
    },
    {
      "holeNumber": 6,
      "yardage": 117,
      "par": 3,
      "handicap": 17
    },
    {
      "holeNumber": 7,
      "yardage": 413,
      "par": 4,
      "handicap": 3
    },
    {
      "holeNumber": 8,
      "yardage": 335,
      "par": 4,
      "handicap": 11
    },
    {
      "holeNumber": 9,
      "yardage": 368,
      "par": 4,
      "handicap": 9
    },
    {
      "holeNumber": 10,
      "yardage": 499,
      "par": 5,
      "handicap": 12
    },
    {
      "holeNumber": 11,
      "yardage": 387,
      "par": 4,
      "handicap": 6
    },
    {
      "holeNumber": 12,
      "yardage": 298,
      "par": 4,
      "handicap": 14
    },
    {
      "holeNumber": 13,
      "yardage": 327,
      "par": 4,
      "handicap": 16
    },
    {
      "holeNumber": 14,
      "yardage": 168,
      "par": 3,
      "handicap": 18
    },
    {
      "holeNumber": 15,
      "yardage": 433,
      "par": 4,
      "handicap": 2
    },
    {
      "holeNumber": 16,
      "yardage": 505,
      "par": 5,
      "handicap": 8
    },
    {
      "holeNumber": 17,
      "yardage": 180,
      "par": 3,
      "handicap": 10
    },
    {
      "holeNumber": 18,
      "yardage": 413,
      "par": 4,
      "handicap": 4
    }
  ]
}

=== nschoena/golf_score_tracker/data/courses/hawley_white.json
{
  "$schema": "./course.schema.json",
  "courseId": 0,
  "courseName": "Hawley Golf & Country Club",
  "tees": "White",
  "courseSide": "All",
  "location": "Hawley, MN",
  "rating": 67.5,
  "slope": 120,
  "yardage": 5773,
  "par": 71,
  "holes": [
    {
      "holeNumber": 1,
      "yardage": 303,
      "par": 4,
      "handicap": 17
    },
    {
      "holeNumber": 2,
      "yardage": 171,
      "par": 3,
      "handicap": 5
    },
    {
      "holeNumber": 3,
      "yardage": 388,
      "par": 4,
      "handicap": 3
    },
    {
      "holeNumber": 4,
      "yardage": 303,
      "par": 4,
      "handicap": 15
    },
    {
      "holeNumber": 5,
      "yardage": 493,
      "par": 5,
      "handicap": 1
    },
    {
      "holeNumber": 6,
      "yardage": 314,
      "par": 4,
      "handicap": 13
    },
    {
      "holeNumber": 7,
      "yardage": 355,
      "par": 4,
      "handicap": 11
    },
    {
      "holeNumber": 8,
      "yardage": 180,
      "par": 3,
      "handicap": 7
    },
    {
      "holeNumber": 9,
      "yardage": 503,
      "par": 5,
      "handicap": 9
    },
    {
      "holeNumber": 10,
      "yardage": 164,
      "par": 3,
      "handicap": 6
    },
    {
      "holeNumber": 11,
      "yardage": 277,
      "par": 4,
      "handicap": 18
    },
    {
      "holeNumber": 12,
      "yardage": 353,
      "par": 4,
      "handicap": 2
    },
    {
      "holeNumber": 13,
      "yardage": 134,
      "par": 3,
      "handicap": 16
    },
    {
      "holeNumber": 14,
      "yardage": 496,
      "par": 5,
      "handicap": 8
    },
    {
      "holeNumber": 15,
      "yardage": 362,
      "par": 4,
      "handicap": 4
    },
    {
      "holeNumber": 16,
      "yardage": 176,
      "par": 3,
      "handicap": 14
    },
    {
      "holeNumber": 17,
      "yardage": 471,
      "par": 5,
      "handicap": 10
    },
    {
      "holeNumber": 18,
      "yardage": 330,
      "par": 4,
      "handicap": 12
    }
  ]
}
