=== nschoena/golf_score_tracker/src/golf_score_tracker/data/scores/score.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/my-data.schema.json",
  "title": "Score document schema",
  "description": "The schema for the score document I am designing.",
  "type": "object",
  "properties": {
    "courseName": {
        "type": "string",
        "description": "The name of the golf course you played."    
    },
    "courseSide": {
        "type": "string",
        "description": "Course section played: Front 9, Back 9, or Full 18",
        "enum": [
            "Front",
            "Back",
            "All"
        ]
    },
    "tees": {
        "type": "string",
        "description": "Name of tees that were played."
    },
    "date": {
        "type": "string",
        "description": "The date the round was played in YYYY-MM-DD.",
        "format": "date"
    },
    "score": {
        "type": "integer",
        "description": "Total score. This could be calculated from the holesPlayed."
    },
    "girPercentage": {
        "type": "number",
        "description": "Percentage of greens hit in regulation. This can be calculated from holesPlayed."
    },
    "teeAccuracy": {
        "type": "array",
        "description": "Percentage breakdown of tee shot accuracy (Missed Left, Hit Fairway, Missed Right). This can be calculated from holesPlayed.",
        "minItems": 3,
        "maxItems": 3,
        "items": [
            { "type": "number", "description": "Percentage missed left."},
            { "type": "number", "description": "Percentage hit fairway."},
            { "type": "number", "description": "Percentage missed right."}
        ]
    },
    "holesPlayed": {
        "type": "array",
        "description": "An ordered list of scores for the golf holes played.",        
        "minItems": 9,
        "maxItems": 18,
        "items": {
            "type": "object",
            "properties": {
                "holeNumber": {"type": "integer"},
                "strokes": {
                    "type": "integer",
                    "description": "Total number of strokes including putts."
                },
                "putts": {
                    "type": "integer",
                    "description": "Total number of putts for this hole."
                },
                "driveResult": {
                    "type": "string",
                    "description": "Result of your drive, Par3TeeShot if par 3",
                    "enum": [
                        "Missed Left",
                        "Hit Fairway",
                        "Missed Right",
                        "Par3TeeShot"
                    ]
                },
                "gir": {
                    "type": "boolean",
                    "description": "True if green in regulation, False if not. This could be calculated using the formula (strokes-putts) - (par-2)"
                }               
            }
        },
        "required": [
            "holeNumber",
            "strokes"
        ]
    }
  },
  "required": [
    "courseName",
    "courseSide",
    "tees",
    "date",
    "score",
    "holesPlayed"
  ]
}

=== nschoena/golf_score_tracker/data/scores/20251004_village_green_white.json
{
    "$schema": "./score.schema.json",
    "courseName": "Village Green Golf Course",
    "courseSide": "All",
    "tees": "White",
    "date": "2025-10-04",
    "score": 79,
    "girPercentage": 56,
    "teeAccuracy": [21.4, 43, 28.6],
    "holesPlayed": [
        {
            "holeNumber": 1,
            "strokes": 4,
            "putts": 1,
            "driveResult": "Missed Right", 
            "gir": false 
        },
        {
            "holeNumber": 2,
            "strokes": 5,
            "putts": 2,
            "driveResult": "Hit Fairway",
            "gir": false 
        },
        {
            "holeNumber": 3,
            "strokes": 5,
            "putts": 2,
            "driveResult": "Hit Fairway",
            "gir": true 
        },
        {
            "holeNumber": 4,
            "strokes": 3,
            "putts": 2,
            "driveResult": "Par3TeeShot",
            "gir": true 
        },
        {
            "holeNumber": 5,
            "strokes": 5,
            "putts": 2,
            "driveResult": "Missed Right",
            "gir": true 
        },
        {
            "holeNumber": 6,
            "strokes": 2,
            "putts": 0,
            "driveResult": "Par3TeeShot",
            "gir": false 
        },
        {
            "holeNumber": 7,
            "strokes": 6,
            "putts": 1,
            "driveResult": "Hit Fairway",
            "gir": false 
        },
        {
            "holeNumber": 8,
            "strokes": 4,
            "putts": 2,
            "driveResult": "Missed Right",
            "gir": true 
        },
        {
            "holeNumber": 9,
            "strokes": 5,
            "putts": 2,
            "driveResult": "Missed Left",
            "gir": false 
        },
        {
            "holeNumber": 10,
            "strokes": 5,
            "putts": 2,
            "driveResult": "Missed Left",
            "gir": true 
        },
        {
            "holeNumber": 11,
            "strokes": 5,
            "putts": 3,
            "driveResult": "Missed Right",
            "gir": true 
        },
        {
            "holeNumber": 12,
            "strokes": 4,
            "putts": 2,
            "driveResult": "Missed Right",
            "gir": true 
        },
        {
            "holeNumber": 13,
            "strokes": 6,
            "putts": 1,
            "driveResult": "Hit Fairway",
            "gir": false 
        },
        {
            "holeNumber": 14,
            "strokes": 3,
            "putts": 2,
            "driveResult": "Par3TeeShot",
            "gir": true 
        },
        {
            "holeNumber": 15,
            "strokes": 5,
            "putts": 2,
            "driveResult": "Missed Left",
            "gir": false 
        },
        {
            "holeNumber": 16,
            "strokes": 4,
            "putts": 3,
            "driveResult": "Hit Fairway",
            "gir": true 
        },
        {
            "holeNumber": 17,
            "strokes": 4,
            "putts": 1,
            "driveResult": "Par3TeeShot",
            "gir": true 
        },
        {
            "holeNumber": 18,
            "strokes": 4,
            "putts": 1,
            "driveResult": "Hit Fairway",
            "gir": false 
        }
        ]
    

}
